server:
  port: 8081

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/UserMicroService
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: User-Service

  config:
    import: configserver:http://localhost:8085


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
       include: health

  endpoint:
     info:
       enabled: true
     health:
       show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        waitDuration: 5s

  rate-limiter:
    instances:
      userRateLimiter:
        limitRefreshPeriod: 2s
        limitForPeriod: 4
        timeoutDuration: 1s






