
server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
       - id: USER-SERVICE
         uri: lb://USER-SERVICE
         predicates:
           - Path=/users/**

       - id: HOTEL-SERVICE
         uri: lb://HOTEL-SERVICE
         predicates:
           - Path=/hotel/** , /staffs/**
#           - to access all url simply place
#           - Path=/**

       - id: RATING-SERVICE
         uri: lb://RATING-SERVICE
         predicates:
           - Path=/ratings/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-13377038.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaepmf2ibQauMTrT5d7
    client-secret: pd5dJZK9qjJRMWtOU5H1kY6RzZzGCAgBFqJMEdwRlEdjRQMyBjnxRKxKeuQKjTIc
    scopes:  openid , profile, email

    redirect-uri: /login/oauth2/code/okta
#  /login/oauth2/code/okta

