server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
      database: microservices
  application:
    name: Rating-Service


okta:
  oauth2:
    issuer: https://dev-13377038.okta.com/oauth2/default
    audience: api://default
